### ISSUE TITLE
x

### ISSUE THREAD

**Issue by Pushplaybang** [tormjens/wp-blade#13]

**Comment by tormjens** [comment]
Good to hear it might fit your project. There should be something in the
docs about custom directives if you did not find it already :)



søn. 28. jan. 2018 kl. 18:36 skrev Paul <notifications@github.com>:

**Comment by Pushplaybang** [comment]
posted this in the wrong repo sorry, had tremendous issues trying to get this to work, and finally gave in and migrated my entire project to sage 9.  Thanks though
