### ISSUE TITLE
How disbale cache in template

### ISSUE THREAD

**Issue by hamedmoody** [tormjens/wp-blade#4]
hi How can i disable cache for blade template?

**Comment by tormjens** [comment]
Blade compiles the templates, so the cache can not be disabled out of the box I'm afraid. 

For theme-templates (the ones in the root of the theme), you can tweak the method `viewExpired` to always return true. This will update the cache every time it is served.

It's however not recommended to compile the templates on every page request. Causes alot of unecessary load.
