### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by 3runoDesign** [tormjens/wp-blade#6]
I'm testing in Digitalocean and was not very successful, you have to give permission to the folders?

**Comment by tormjens** [comment]
I'm not sure. Digital Ocean has many different enviroments, and you can set them up however you'd like, so you'd need to be more specific.

As a general rule both the cache-directory and the views-directory should be somewhat writeable.

**Comment by 3runoDesign** [comment]
@tormjens that's right, I had to the write access.

**Comment by tormjens** [comment]
Awesome. Glad you figured it out. :)
